---
- homebrew: name={{ item }} state=latest
  with_items:
    - go
    - git
    - mercurial

- file: path={{ osx_go_gopath }} state=directory

- template: src=go.zsh.j2 dest={{ zsh_custom_dir }}/go.zsh
